version: '2'
services:
  test1-mysql:
    image: mysql:8.0.20
    # volumes:
    #     - ~/volumes/hr/test1/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=db_cstl
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
